# Generated by Django 5.2.9 on 2026-02-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medicalrecord",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Medical Record",
                "verbose_name_plural": "Medical Records",
            },
        ),
        migrations.RemoveField(
            model_name="medicalrecord",
            name="additional_data",
        ),
        migrations.RemoveField(
            model_name="medicalrecord",
            name="record_date",
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="analysis_components",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Component scores used in fuzzy logic calculation",
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="fuzzy_membership",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Fuzzy membership values for risk categories",
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="patient_age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="risk_score",
            field=models.FloatField(
                default=0.0, help_text="Composite risk score from fuzzy logic"
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="severe_symptoms_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="symptoms_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="medicalrecord",
            index=models.Index(
                fields=["patient", "created_at"], name="core_medica_patient_13c271_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicalrecord",
            index=models.Index(
                fields=["risk_level", "confidence_score"],
                name="core_medica_risk_le_dc3959_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicalrecord",
            index=models.Index(
                fields=["created_by", "created_at"],
                name="core_medica_created_f1fd37_idx",
            ),
        ),
    ]
