# Generated by Django 4.2.28 on 2026-02-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_medicalrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='past_history_file',
            field=models.FileField(blank=True, null=True, upload_to='medical_history/'),
        ),
    ]
