# Generated by Django 4.2.28 on 2026-03-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_medicalrecord_past_history_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='ai_heatmap',
            field=models.ImageField(blank=True, null=True, upload_to='heatmaps/'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='ai_prediction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='ai_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
