# Generated by Django 4.2.28 on 2026-03-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_medicaldocument_ai_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
