# Generated by Django 4.2.28 on 2026-03-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_medicaldocument_ai_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldocument',
            name='document_type',
            field=models.CharField(choices=[('lab_report', 'Lab Report'), ('xray_pneumonia', 'X-Ray - Pneumonia'), ('xray_fracture', 'X-Ray - Bone Fracture'), ('mri', 'MRI - Brain Tumor'), ('ct_scan', 'CT Scan'), ('discharge_summary', 'Discharge Summary'), ('medical_certificate', 'Medical Certificate'), ('insurance_form', 'Insurance Form'), ('other', 'Other')], max_length=50),
        ),
    ]
