# Generated by Django 4.2.28 on 2026-03-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_medicaldocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='ai_frac_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='ai_frac_heatmap',
            field=models.ImageField(blank=True, null=True, upload_to='heatmaps/frac/'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='ai_frac_prediction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='ai_frac_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='ai_mri_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='ai_mri_heatmap',
            field=models.ImageField(blank=True, null=True, upload_to='heatmaps/mri/'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='ai_mri_prediction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='ai_mri_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='ai_pneu_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='ai_pneu_heatmap',
            field=models.ImageField(blank=True, null=True, upload_to='heatmaps/pneu/'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='ai_pneu_prediction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='ai_pneu_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
