# Generated by Django 4.2.28 on 2026-03-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_medicaldocument_ai_frac_confidence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaldocument',
            name='ai_frac_confidence',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='ai_frac_heatmap',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='ai_frac_prediction',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='ai_frac_summary',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='ai_mri_confidence',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='ai_mri_heatmap',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='ai_mri_prediction',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='ai_mri_summary',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='ai_pneu_confidence',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='ai_pneu_heatmap',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='ai_pneu_prediction',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='ai_pneu_summary',
        ),
        migrations.AddField(
            model_name='user',
            name='clinic_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='qualifications',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
