# Generated by Django 4.2.28 on 2026-03-01 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_medicaldocument_ai_frac_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('diagnosis', models.TextField()),
                ('treatment_from', models.DateField()),
                ('treatment_to', models.DateField(blank=True, null=True)),
                ('rest_advised_from', models.DateField(blank=True, null=True)),
                ('rest_advised_to', models.DateField(blank=True, null=True)),
                ('fit_to_resume_date', models.DateField(blank=True, null=True)),
                ('additional_advice', models.TextField(blank=True)),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Certificate',
                'verbose_name_plural': 'Medical Certificates',
                'ordering': ['-issued_date', '-created_at'],
            },
        ),
    ]
