# Generated by Django 4.2.28 on 2026-03-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_emrprediction_updated_at_dataaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_video_consultation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
